In [33]:
import numpy as np

In [34]:
import pandas as pd

In [35]:
hostels = pd.read_csv('HostelFinder.hostels.csv')

In [36]:
hostels.head(1)

_id        lng        lat  price  \
0  64c387aefc06642f2440febe  85.333417  27.703133  10500   

                   title                                        description  \
0  Five Star Boys Hostel  Five Star Boys Hostel one of the hostels in Ka...   

                                   img_collection[0] img_collection[1]  \
0  http://localhost:8000/uploads/2023-07-28T09-18...               NaN   

  img_collection[2] img_collection[3]  ...  \
0               NaN               NaN  ...   

                                address     catagory  \
0  Maitidevi, Kathmandu, Bagmati, Nepal  Boys hostel   

                                            features  \
0  24 hours electricity,Hot and Cold water,Launda...   

                        uid       uName           uEmail      uPhone  \
0  64bd52dadb1d17cc33ae50f1  dhamisuraj  dhami@gmail.com  9860547079   

                  createdAt                 updatedAt __v  
0  2023-07-28T09:17:34.719Z  2023-07-28T09:18:00.698Z   1  

[1 rows x 21 columns]

In [37]:
print(hostels.columns)

Index(['_id', 'lng', 'lat', 'price', 'title', 'description',
       'img_collection[0]', 'img_collection[1]', 'img_collection[2]',
       'img_collection[3]', 'phone', 'address', 'catagory', 'features', 'uid',
       'uName', 'uEmail', 'uPhone', 'createdAt', 'updatedAt', '__v'],
      dtype='object')


In [38]:
hostels = hostels[['_id', 'title', 'description', 'address','catagory','features','price', 'lng', 'lat']]

In [39]:
hostels.head()

_id                   title  \
0  64c387aefc06642f2440febe   Five Star Boys Hostel   
1  64c38877fc06642f2440fec9  Third Eyes Boys Hostel   
2  64c388dbfc06642f2440fecc      Shivam Boys Hostel   
3  64c389d6fc06642f2440fed7     Nepzone Boys Hostel   
4  64c38b06fc06642f2440feda   Samunnati Boys Hostel   

                                         description  \
0  Five Star Boys Hostel one of the hostels in Ka...   
1  Third Eye Boys Hostel offers you services like...   
2  Shivam Boys Hostel is located in Gyaneshwor, t...   
3  Nepzone Boys Hostel is located at the very cor...   
4  Samunnati Boys Hostel can provide a comfortabl...   

                                             address     catagory  \
0               Maitidevi, Kathmandu, Bagmati, Nepal  Boys hostel   
1            Bhojan Griha, Kathmandu, Bagmati, Nepal  Boys hostel   
2  Galaxy Public School, Dillibajar, Kathmandu, B...  Boys hostel   
3    Charkhal, Dillibazar, Kathmandu, Bagmati, Nepal  Boys hostel   
4              Dillibazar, Kathmandu, Bagmati, Nepal  Boys hostel   

                                            features  price        lng  \
0  24 hours electricity,Hot and Cold water,Launda...  10500  85.333417   
1  24 hours electricity,Hot and Cold water,Launda...   9500  85.327202   
2  Hot and Cold water,24 hours electricity,Launda...   9500  85.330546   
3  CCTV,Security Guard,Parking Lot,Locker room,Wi...   9499  85.328554   
4  24 hours electricity,Hot and Cold water,Launda...  10000  85.328221   

         lat  
0  27.703133  
1  27.705343  
2  27.708978  
3  27.706303  
4  27.704821

In [40]:
print(hostels.columns)

Index(['_id', 'title', 'description', 'address', 'catagory', 'features',
       'price', 'lng', 'lat'],
      dtype='object')


In [41]:
hostels.isnull().sum()

_id            0
title          0
description    0
address        0
catagory       0
features       0
price          0
lng            0
lat            0
dtype: int64

In [42]:
hostels.duplicated().sum()

0

In [43]:
hostels['title'] = hostels['title'].apply(lambda x:x.split())

In [44]:
hostels['description'] = hostels['description'].apply(lambda x:x.split())

In [45]:
hostels['address'] = hostels['address'].apply(lambda x:x.split())

In [46]:
hostels['features'] = hostels['features'].apply(lambda x:x.split())

In [47]:
hostels.head()

_id                        title  \
0  64c387aefc06642f2440febe   [Five, Star, Boys, Hostel]   
1  64c38877fc06642f2440fec9  [Third, Eyes, Boys, Hostel]   
2  64c388dbfc06642f2440fecc       [Shivam, Boys, Hostel]   
3  64c389d6fc06642f2440fed7      [Nepzone, Boys, Hostel]   
4  64c38b06fc06642f2440feda    [Samunnati, Boys, Hostel]   

                                         description  \
0  [Five, Star, Boys, Hostel, one, of, the, hoste...   
1  [Third, Eye, Boys, Hostel, offers, you, servic...   
2  [Shivam, Boys, Hostel, is, located, in, Gyanes...   
3  [Nepzone, Boys, Hostel, is, located, at, the, ...   
4  [Samunnati, Boys, Hostel, can, provide, a, com...   

                                             address     catagory  \
0          [Maitidevi,, Kathmandu,, Bagmati,, Nepal]  Boys hostel   
1      [Bhojan, Griha,, Kathmandu,, Bagmati,, Nepal]  Boys hostel   
2  [Galaxy, Public, School,, Dillibajar,, Kathman...  Boys hostel   
3  [Charkhal,, Dillibazar,, Kathmandu,, Bagmati,,...  Boys hostel   
4         [Dillibazar,, Kathmandu,, Bagmati,, Nepal]  Boys hostel   

                                            features  price        lng  \
0  [24, hours, electricity,Hot, and, Cold, water,...  10500  85.333417   
1  [24, hours, electricity,Hot, and, Cold, water,...   9500  85.327202   
2  [Hot, and, Cold, water,24, hours, electricity,...   9500  85.330546   
3  [CCTV,Security, Guard,Parking, Lot,Locker, roo...   9499  85.328554   
4  [24, hours, electricity,Hot, and, Cold, water,...  10000  85.328221   

         lat  
0  27.703133  
1  27.705343  
2  27.708978  
3  27.706303  
4  27.704821

In [49]:
hostels['title'] = hostels['title'].apply(lambda x:[i.replace(" ","") for i in x])

In [50]:
hostels['description'] = hostels['description'].apply(lambda x:[i.replace(" ","") for i in x])

In [51]:
hostels['address'] = hostels['address'].apply(lambda x:[i.replace(" ","") for i in x])

In [52]:
hostels['features'] = hostels['features'].apply(lambda x:[i.replace(" ","") for i in x])

In [53]:
hostels.head()

_id                        title  \
0  64c387aefc06642f2440febe   [Five, Star, Boys, Hostel]   
1  64c38877fc06642f2440fec9  [Third, Eyes, Boys, Hostel]   
2  64c388dbfc06642f2440fecc       [Shivam, Boys, Hostel]   
3  64c389d6fc06642f2440fed7      [Nepzone, Boys, Hostel]   
4  64c38b06fc06642f2440feda    [Samunnati, Boys, Hostel]   

                                         description  \
0  [Five, Star, Boys, Hostel, one, of, the, hoste...   
1  [Third, Eye, Boys, Hostel, offers, you, servic...   
2  [Shivam, Boys, Hostel, is, located, in, Gyanes...   
3  [Nepzone, Boys, Hostel, is, located, at, the, ...   
4  [Samunnati, Boys, Hostel, can, provide, a, com...   

                                             address     catagory  \
0          [Maitidevi,, Kathmandu,, Bagmati,, Nepal]  Boys hostel   
1      [Bhojan, Griha,, Kathmandu,, Bagmati,, Nepal]  Boys hostel   
2  [Galaxy, Public, School,, Dillibajar,, Kathman...  Boys hostel   
3  [Charkhal,, Dillibazar,, Kathmandu,, Bagmati,,...  Boys hostel   
4         [Dillibazar,, Kathmandu,, Bagmati,, Nepal]  Boys hostel   

                                            features  price        lng  \
0  [24, hours, electricity,Hot, and, Cold, water,...  10500  85.333417   
1  [24, hours, electricity,Hot, and, Cold, water,...   9500  85.327202   
2  [Hot, and, Cold, water,24, hours, electricity,...   9500  85.330546   
3  [CCTV,Security, Guard,Parking, Lot,Locker, roo...   9499  85.328554   
4  [24, hours, electricity,Hot, and, Cold, water,...  10000  85.328221   

         lat  
0  27.703133  
1  27.705343  
2  27.708978  
3  27.706303  
4  27.704821

In [54]:
hostels['tags'] = hostels['title'] + hostels['description'] + hostels['address'] + hostels['features']

In [55]:
hostels.head()

_id                        title  \
0  64c387aefc06642f2440febe   [Five, Star, Boys, Hostel]   
1  64c38877fc06642f2440fec9  [Third, Eyes, Boys, Hostel]   
2  64c388dbfc06642f2440fecc       [Shivam, Boys, Hostel]   
3  64c389d6fc06642f2440fed7      [Nepzone, Boys, Hostel]   
4  64c38b06fc06642f2440feda    [Samunnati, Boys, Hostel]   

                                         description  \
0  [Five, Star, Boys, Hostel, one, of, the, hoste...   
1  [Third, Eye, Boys, Hostel, offers, you, servic...   
2  [Shivam, Boys, Hostel, is, located, in, Gyanes...   
3  [Nepzone, Boys, Hostel, is, located, at, the, ...   
4  [Samunnati, Boys, Hostel, can, provide, a, com...   

                                             address     catagory  \
0          [Maitidevi,, Kathmandu,, Bagmati,, Nepal]  Boys hostel   
1      [Bhojan, Griha,, Kathmandu,, Bagmati,, Nepal]  Boys hostel   
2  [Galaxy, Public, School,, Dillibajar,, Kathman...  Boys hostel   
3  [Charkhal,, Dillibazar,, Kathmandu,, Bagmati,,...  Boys hostel   
4         [Dillibazar,, Kathmandu,, Bagmati,, Nepal]  Boys hostel   

                                            features  price        lng  \
0  [24, hours, electricity,Hot, and, Cold, water,...  10500  85.333417   
1  [24, hours, electricity,Hot, and, Cold, water,...   9500  85.327202   
2  [Hot, and, Cold, water,24, hours, electricity,...   9500  85.330546   
3  [CCTV,Security, Guard,Parking, Lot,Locker, roo...   9499  85.328554   
4  [24, hours, electricity,Hot, and, Cold, water,...  10000  85.328221   

         lat                                               tags  
0  27.703133  [Five, Star, Boys, Hostel, Five, Star, Boys, H...  
1  27.705343  [Third, Eyes, Boys, Hostel, Third, Eye, Boys, ...  
2  27.708978  [Shivam, Boys, Hostel, Shivam, Boys, Hostel, i...  
3  27.706303  [Nepzone, Boys, Hostel, Nepzone, Boys, Hostel,...  
4  27.704821  [Samunnati, Boys, Hostel, Samunnati, Boys, Hos...

In [56]:
hostels['tags'][0]

['Five',
 'Star',
 'Boys',
 'Hostel',
 'Five',
 'Star',
 'Boys',
 'Hostel',
 'one',
 'of',
 'the',
 'hostels',
 'in',
 'Kathmandu',
 'located',
 'in',
 'Maitidevi',
 'gains',
 'popularity',
 'day',
 'by',
 'day',
 'by',
 'servicing',
 'its',
 'students,',
 'providing',
 'required',
 'facilities,',
 'and',
 'making',
 'them',
 'involved',
 'in',
 'different',
 'creative',
 'activities.',
 'Prices:',
 'Single',
 'Seater',
 '-',
 'Rs.16000,',
 '2',
 'Seater',
 '-',
 'Rs.11500,',
 '3',
 'Seater',
 '-',
 'Rs.11000,',
 '4',
 'Seater',
 '-',
 'Rs.10500.',
 'Maitidevi,',
 'Kathmandu,',
 'Bagmati,',
 'Nepal',
 '24',
 'hours',
 'electricity,Hot',
 'and',
 'Cold',
 'water,Laundary,Wifi,Locker',
 'room,Parking',
 'Lot,Security',
 'Guard,CCTV']

In [58]:
hostels['tags'] = hostels['tags'].apply(lambda x: " ".join([tag.replace("', '", " ").replace("['", "").replace("']", "") for tag in x]))

In [59]:
hostels['tags'][0]

'Five Star Boys Hostel Five Star Boys Hostel one of the hostels in Kathmandu located in Maitidevi gains popularity day by day by servicing its students, providing required facilities, and making them involved in different creative activities. Prices: Single Seater - Rs.16000, 2 Seater - Rs.11500, 3 Seater - Rs.11000, 4 Seater - Rs.10500. Maitidevi, Kathmandu, Bagmati, Nepal 24 hours electricity,Hot and Cold water,Laundary,Wifi,Locker room,Parking Lot,Security Guard,CCTV'

In [60]:
hostels['tags'] = hostels['tags'].apply(lambda x: x.replace("'", "").replace('"', ''))

In [61]:
hostels['tags'][0]

'Five Star Boys Hostel Five Star Boys Hostel one of the hostels in Kathmandu located in Maitidevi gains popularity day by day by servicing its students, providing required facilities, and making them involved in different creative activities. Prices: Single Seater - Rs.16000, 2 Seater - Rs.11500, 3 Seater - Rs.11000, 4 Seater - Rs.10500. Maitidevi, Kathmandu, Bagmati, Nepal 24 hours electricity,Hot and Cold water,Laundary,Wifi,Locker room,Parking Lot,Security Guard,CCTV'

In [62]:
new_df = hostels[['_id','price','lng','lat','tags']]

In [66]:
new_df

_id  price        lng        lat  \
0   64c387aefc06642f2440febe  10500  85.333417  27.703133   
1   64c38877fc06642f2440fec9   9500  85.327202  27.705343   
2   64c388dbfc06642f2440fecc   9500  85.330546  27.708978   
3   64c389d6fc06642f2440fed7   9499  85.328554  27.706303   
4   64c38b06fc06642f2440feda  10000  85.328221  27.704821   
5   64c38baffc06642f2440fedd   9998  85.323574  27.705715   
6   64c38c59fc06642f2440fee0  11000  85.328574  27.701492   
7   64c38cd4fc06642f2440fee3   9498  85.340689  27.702040   
8   64c38d80fc06642f2440fee6   9499  85.323574  27.705715   
9   64c38fc5fc06642f2440fef7  10000  85.328899  27.692926   
10  64c3916ffc06642f2440fefc   9500  85.332398  27.703880   
11  64c39289fc06642f2440feff   9500  85.326719  27.690674   
12  64c393eefc06642f2440ff02  10000  85.346521  27.684178   
13  64c39627fc06642f2440ff0e  10000  85.337838  27.690617   
14  64c396dafc06642f2440ff12   9498  85.323379  27.705876   
15  64c397b0fc06642f2440ff15   9500  85.338072  27.692621   
16  64c3989afc06642f2440ff18   9500  85.350423  27.699184   
17  64c399c5fc06642f2440ff1b  11500  85.323876  27.700940   
18  64c39a98fc06642f2440ff1e  10000  85.327530  27.705463   
19  64c39e42fc06642f2440ff2a   9500  85.319364  27.705502   
20  64c39ebffc06642f2440ff2d   9500  85.339572  27.724217   
21  64c39f5ffc06642f2440ff30  10000  85.340804  27.692629   
22  64c3a1b9fc06642f2440ff36   9500  85.345611  27.684622   
23  64c3a23bfc06642f2440ff39   9000  85.342568  27.687480   
24  64c3a314fc06642f2440ff3e   9500  85.345803  27.683149   
25  64c3a3aefc06642f2440ff41   9500  85.335972  27.705841   
26  64c3a45cfc06642f2440ff44   9500  85.329258  27.687234   
27  64c3a4eafc06642f2440ff47   9500  85.306774  27.720559   
28  64c3a5b8fc06642f2440ff4a   9500  85.327868  27.693775   
29  64c3a6dcfc06642f2440ff57  10000  85.347324  27.679172   
30  64c3a749fc06642f2440ff5a  10000  85.323315  27.705383   
31  64c3a7ccfc06642f2440ff5d  10000  85.282302  27.674993   
32  64c3a86efc06642f2440ff60  10000  85.340747  27.670741   
33  64c3a8d2fc06642f2440ff63   9000  85.336297  27.693075   
34  64c3aa1ffc06642f2440ff69  12000  85.321968  27.705193   
35  64c3aab8fc06642f2440ff6c   9500  85.338684  27.685019   
36  64c3ab0efc06642f2440ff6f   9999  85.323150  27.692272   
37  64c3ab69fc06642f2440ff72  10000  85.333232  27.684375   
38  64c3abe3fc06642f2440ff75   9500  85.340643  27.685096   
39  64c3ac7afc06642f2440ff78   8998  85.344831  27.699719   
40  64c3acddfc06642f2440ff7b   9000  85.347346  27.699214   
41  64c3ad73fc06642f2440ff7e   9500  85.327843  27.694286   
42  64c3adddfc06642f2440ff81  10000  85.341509  27.705676   
43  64c3aeffcc2695cc982ef8d1   9500  85.328283  27.687243   
44  64c3af5bcc2695cc982ef8d4   9500  85.350423  27.699184   
45  64c3afeecc2695cc982ef8d7  10000  85.328205  27.688182   
46  64c3b05ecc2695cc982ef8db  10000  85.312655  27.724955   
47  64c3b10dcc2695cc982ef8de   9598  85.311697  27.716883   
48  64c3b1b3cc2695cc982ef8e8  10500  85.328280  27.701735   
49  64c3b40dcc2695cc982ef8f3  12500  85.342960  27.678767   

                                                 tags  
0   Five Star Boys Hostel Five Star Boys Hostel on...  
1   Third Eyes Boys Hostel Third Eye Boys Hostel o...  
2   Shivam Boys Hostel Shivam Boys Hostel is locat...  
3   Nepzone Boys Hostel Nepzone Boys Hostel is loc...  
4   Samunnati Boys Hostel Samunnati Boys Hostel ca...  
5   City Delux Boys Hostel City Deluxe Boys Hostel...  
6   Yakso Boys Hostel Yakso Boys Hostel offers aff...  
7   Siddhababa Boys Hostel Sidhababa Boys Hostel i...  
8   Samul Boys Hostel Samul Boys Hostel offers you...  
9   Peaceful Girls Hostel Peaceful Girls Hostel fa...  
10  Balaji Boys Hostel Balaji Boys Hostel has focu...  
11  New Hill Boys Hostel New Hill Boys Hostel serv...  
12  AR Boys Hostel A R Boys Hostel located at Mith...  
13  Novelty Boys Hostel Novelty Boys Hostel prefer...  
14  Mount Everest Boys Hostel Meet people from all...  
15  Happy Home Bo

In [67]:
new_df['tags'][0]

'Five Star Boys Hostel Five Star Boys Hostel one of the hostels in Kathmandu located in Maitidevi gains popularity day by day by servicing its students, providing required facilities, and making them involved in different creative activities. Prices: Single Seater - Rs.16000, 2 Seater - Rs.11500, 3 Seater - Rs.11000, 4 Seater - Rs.10500. Maitidevi, Kathmandu, Bagmati, Nepal 24 hours electricity,Hot and Cold water,Laundary,Wifi,Locker room,Parking Lot,Security Guard,CCTV'

In [68]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\empsw\AppData\Local\Temp\ipykernel_4168\3214958533.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())


In [69]:
new_df['tags'][0]

'five star boys hostel five star boys hostel one of the hostels in kathmandu located in maitidevi gains popularity day by day by servicing its students, providing required facilities, and making them involved in different creative activities. prices: single seater - rs.16000, 2 seater - rs.11500, 3 seater - rs.11000, 4 seater - rs.10500. maitidevi, kathmandu, bagmati, nepal 24 hours electricity,hot and cold water,laundary,wifi,locker room,parking lot,security guard,cctv'

In [70]:
!pip install nltk

In [71]:
import nltk

In [72]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [73]:
def stem(text):
    y = []
    
    for i in text.split():
        y.append(ps.stem(i))
        
    return " ".join(y)

In [74]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\empsw\AppData\Local\Temp\ipykernel_4168\3213734980.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)


In [75]:
new_df['tags'][0]

'five star boy hostel five star boy hostel one of the hostel in kathmandu locat in maitidevi gain popular day by day by servic it students, provid requir facilities, and make them involv in differ creativ activities. prices: singl seater - rs.16000, 2 seater - rs.11500, 3 seater - rs.11000, 4 seater - rs.10500. maitidevi, kathmandu, bagmati, nepal 24 hour electricity,hot and cold water,laundary,wifi,lock room,park lot,secur guard,cctv'

In [76]:
ps.stem('loved')

'love'

In [77]:
ps.stem('loving')

'love'

In [82]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=1000,stop_words='english')

In [83]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [84]:
vectors[0]

array([0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [88]:
feature_names = cv.get_feature_names_out()

In [90]:
from sklearn.metrics.pairwise import cosine_similarity

In [91]:
similaritytags = cosine_similarity(vectors)

In [92]:
similaritytags

array([[1.        , 0.50858153, 0.49000655, ..., 0.24890721, 0.43969585,
        0.35391769],
       [0.50858153, 1.        , 0.74474568, ..., 0.35939099, 0.58474501,
        0.50470424],
       [0.49000655, 0.74474568, 1.        , ..., 0.36114822, 0.54997429,
        0.49186938],
       ...,
       [0.24890721, 0.35939099, 0.36114822, ..., 1.        , 0.26819409,
        0.31648105],
       [0.43969585, 0.58474501, 0.54997429, ..., 0.26819409, 1.        ,
        0.44136741],
       [0.35391769, 0.50470424, 0.49186938, ..., 0.31648105, 0.44136741,
        1.        ]])

In [93]:
similaritytags[0]

array([1.        , 0.50858153, 0.49000655, 0.40969803, 0.73223829,
       0.46032322, 0.44513406, 0.50202095, 0.46032322, 0.39000527,
       0.45878219, 0.56605398, 0.48100649, 0.46415825, 0.42214126,
       0.44589438, 0.45518577, 0.52862282, 0.44943516, 0.40069622,
       0.39987934, 0.6024971 , 0.36522076, 0.43648986, 0.4132966 ,
       0.51241994, 0.47751959, 0.48821155, 0.45949322, 0.42474977,
       0.50134821, 0.39051186, 0.39051186, 0.34003312, 0.47329261,
       0.40420249, 0.48723285, 0.41261407, 0.37666339, 0.31383427,
       0.31127231, 0.61313052, 0.45954761, 0.46408434, 0.40977912,
       0.44872385, 0.50076564, 0.24890721, 0.43969585, 0.35391769])

In [94]:
from sklearn.preprocessing import MinMaxScaler

In [95]:
price_values = new_df['price']

In [96]:
# Initialize the MinMaxScaler
scaler = MinMaxScaler()

In [97]:
# Reshape the price values to a 2D array (required by the scaler)
price_values_2d = price_values.values.reshape(-1, 1)

In [98]:
# Fit and transform the price values using the scaler
normalized_price = scaler.fit_transform(price_values_2d)

In [99]:
# Flatten the normalized price values to a 1D array
normalized_price = normalized_price.flatten()

In [100]:
# Calculate similarity based on price difference
price_difference = np.abs(normalized_price - normalized_price[:, np.newaxis])
price_similarity = 1 - price_difference

In [101]:
price_similarity

array([[1.        , 0.71444889, 0.71444889, ..., 0.7424329 , 1.        ,
        0.42889777],
       [0.71444889, 1.        , 1.        , ..., 0.97201599, 0.71444889,
        0.14334666],
       [0.71444889, 1.        , 1.        , ..., 0.97201599, 0.71444889,
        0.14334666],
       ...,
       [0.7424329 , 0.97201599, 0.97201599, ..., 1.        , 0.7424329 ,
        0.17133067],
       [1.        , 0.71444889, 0.71444889, ..., 0.7424329 , 1.        ,
        0.42889777],
       [0.42889777, 0.14334666, 0.14334666, ..., 0.17133067, 0.42889777,
        1.        ]])

In [102]:
price_similarity[0]

array([1.        , 0.71444889, 0.71444889, 0.71416334, 0.85722444,
       0.85665334, 0.85722444, 0.71387778, 0.71416334, 0.85722444,
       0.71444889, 0.71444889, 0.85722444, 0.85722444, 0.71387778,
       0.71444889, 0.71444889, 0.71444889, 0.85722444, 0.71444889,
       0.71444889, 0.85722444, 0.71444889, 0.57167333, 0.71444889,
       0.71444889, 0.71444889, 0.71444889, 0.71444889, 0.85722444,
       0.85722444, 0.85722444, 0.85722444, 0.57167333, 0.57167333,
       0.71444889, 0.85693889, 0.85722444, 0.71444889, 0.57110223,
       0.57167333, 0.71444889, 0.85722444, 0.71444889, 0.71444889,
       0.85722444, 0.85722444, 0.7424329 , 1.        , 0.42889777])

In [103]:
price_similarity[48]

array([1.        , 0.71444889, 0.71444889, 0.71416334, 0.85722444,
       0.85665334, 0.85722444, 0.71387778, 0.71416334, 0.85722444,
       0.71444889, 0.71444889, 0.85722444, 0.85722444, 0.71387778,
       0.71444889, 0.71444889, 0.71444889, 0.85722444, 0.71444889,
       0.71444889, 0.85722444, 0.71444889, 0.57167333, 0.71444889,
       0.71444889, 0.71444889, 0.71444889, 0.71444889, 0.85722444,
       0.85722444, 0.85722444, 0.85722444, 0.57167333, 0.57167333,
       0.71444889, 0.85693889, 0.85722444, 0.71444889, 0.57110223,
       0.57167333, 0.71444889, 0.85722444, 0.71444889, 0.71444889,
       0.85722444, 0.85722444, 0.7424329 , 1.        , 0.42889777])

In [104]:
price_similarity[2]

array([0.71444889, 1.        , 1.        , 0.99971445, 0.85722444,
       0.85779555, 0.57167333, 0.9994289 , 0.99971445, 0.85722444,
       1.        , 1.        , 0.85722444, 0.85722444, 0.9994289 ,
       1.        , 1.        , 0.42889777, 0.85722444, 1.        ,
       1.        , 0.85722444, 1.        , 0.85722444, 1.        ,
       1.        , 1.        , 1.        , 1.        , 0.85722444,
       0.85722444, 0.85722444, 0.85722444, 0.85722444, 0.28612222,
       1.        , 0.85750999, 0.85722444, 1.        , 0.85665334,
       0.85722444, 1.        , 0.85722444, 1.        , 1.        ,
       0.85722444, 0.85722444, 0.97201599, 0.71444889, 0.14334666])

In [105]:
lat_values = new_df['lat'].values
lng_values = new_df['lng'].values

In [106]:
from math import radians, sin, cos, sqrt, atan2

In [107]:
# Define a function to calculate the Haversine distance
def haversine(lat1, lng1, lat2, lng2):
    # Convert latitude and longitude from degrees to radians
    lat1_rad = np.radians(lat1)
    lng1_rad = np.radians(lng1)
    lat2_rad = np.radians(lat2)
    lng2_rad = np.radians(lng2)

    # Haversine formula
    dlat = lat2_rad - lat1_rad
    dlng = lng2_rad - lng1_rad
    a = np.sin(dlat/2) ** 2 + np.cos(lat1_rad) * np.cos(lat2_rad) * np.sin(dlng/2) ** 2
    c = 2 * np.arcsin(np.sqrt(a))
    r = 6371  # Radius of the Earth in kilometers
    distance = c * r

    # Similarity based on distance
    similarity = 1 / (1 + distance)

    return similarity

In [108]:
distance_similarity = haversine(lat_values[:, np.newaxis], lng_values[np.newaxis, :], lat_values[np.newaxis, :], lng_values[:, np.newaxis])

In [109]:
distance_similarity

array([[1.        , 0.60264876, 0.58524701, ..., 0.27559088, 0.65396849,
        0.25855195],
       [0.60264876, 1.        , 0.65734885, ..., 0.33399508, 0.70670973,
        0.23053818],
       [0.58524701, 0.65734885, 1.        , ..., 0.32752292, 0.54474803,
        0.21859253],
       ...,
       [0.27559088, 0.33399508, 0.32752292, ..., 1.        , 0.29889702,
        0.16030676],
       [0.65396849, 0.70670973, 0.54474803, ..., 0.29889702, 1.        ,
        0.25415554],
       [0.25855195, 0.23053818, 0.21859253, ..., 0.16030676, 0.25415554,
        1.        ]])

In [110]:
distance_similarity[0]

array([1.        , 0.60264876, 0.58524701, 0.62716649, 0.64731305,
       0.49735046, 0.66200335, 0.57931938, 0.49735046, 0.45064202,
       0.88476379, 0.39457513, 0.28808426, 0.40679676, 0.4915851 ,
       0.44336089, 0.36618898, 0.50749941, 0.6117014 , 0.41523061,
       0.29227667, 0.42089842, 0.29560902, 0.33785081, 0.28290503,
       0.71817343, 0.35527537, 0.23469105, 0.45971578, 0.25027668,
       0.49369545, 0.14437867, 0.21397738, 0.46429498, 0.46508011,
       0.32469403, 0.38836657, 0.32405645, 0.31969193, 0.45743169,
       0.41001491, 0.47027748, 0.54190841, 0.35238518, 0.36618898,
       0.3649782 , 0.23966292, 0.27559088, 0.65396849, 0.25855195])

In [111]:
#weight for combined similarity
weight_tags = 0.3
weight_price = 0.3 
weight_distance = 0.4

In [112]:
combined_similarity = (
    weight_tags * similaritytags +
    weight_price * price_similarity +
    weight_distance * distance_similarity
)

In [113]:
combined_similarity

array([[1.        , 0.60796863, 0.59543544, ..., 0.40763838, 0.69349615,
        0.33826542],
       [0.60796863, 1.        , 0.78636324, ..., 0.53302012, 0.67244206,
        0.28663054],
       [0.59543544, 0.78636324, 1.        , ..., 0.53095843, 0.59722617,
        0.27800182],
       ...,
       [0.40763838, 0.53302012, 0.53095843, ..., 1.        , 0.42274691,
        0.21046622],
       [0.69349615, 0.67244206, 0.59722617, ..., 0.42274691, 1.        ,
        0.36274177],
       [0.33826542, 0.28663054, 0.27800182, ..., 0.21046622, 0.36274177,
        1.        ]])

In [114]:
combined_similarity[0]

array([1.        , 0.60796863, 0.59543544, 0.58802501, 0.73576404,
       0.59403315, 0.65550889, 0.59649737, 0.55128615, 0.55442572,
       0.70587484, 0.54198091, 0.51670298, 0.55913351, 0.53743975,
       0.52544734, 0.49736599, 0.57592127, 0.63667844, 0.50063578,
       0.45120914, 0.60627583, 0.4421445 , 0.43758928, 0.45148566,
       0.65533002, 0.49970069, 0.45467455, 0.53606895, 0.48470294,
       0.60504998, 0.43207236, 0.45991184, 0.45922993, 0.49952182,
       0.46547302, 0.55859815, 0.51057413, 0.45521045, 0.44845363,
       0.42888966, 0.58638482, 0.61179498, 0.49451404, 0.48374399,
       0.53777577, 0.50326219, 0.40763838, 0.69349615, 0.33826542])

In [115]:
combined_similarity[0].shape

(50,)

In [116]:
sorted(list(enumerate(combined_similarity[0])),reverse=True,key=lambda x:x[1])

[(0, 1.0),
 (4, 0.7357640366852596),
 (10, 0.7058748402479099),
 (48, 0.6934961522946308),
 (6, 0.6555088887487255),
 (25, 0.6553300203306327),
 (18, 0.6366784417264493),
 (42, 0.6117949787995551),
 (1, 0.6079686315920283),
 (21, 0.6062758323682873),
 (30, 0.6050499763581042),
 (7, 0.5964973727937858),
 (2, 0.5954354350214976),
 (5, 0.5940331529208326),
 (3, 0.5880250057826649),
 (41, 0.5863848150210298),
 (17, 0.5759212745779594),
 (13, 0.5591335092896461),
 (36, 0.5585981509958323),
 (9, 0.554425722274039),
 (8, 0.5512861512075259),
 (11, 0.5419809134232273),
 (45, 0.5377757681264943),
 (14, 0.5374397520285638),
 (28, 0.536068945724361),
 (15, 0.5254473366593131),
 (12, 0.5167029831929876),
 (37, 0.5105741316569214),
 (46, 0.5032621937755725),
 (19, 0.5006357774007161),
 (26, 0.4997006907403456),
 (34, 0.4995218228765913),
 (16, 0.497365989799078),
 (43, 0.4945140391226819),
 (29, 0.4847029381705192),
 (44, 0.48374399410715074),
 (35, 0.4654730228223317),
 (32, 0.45991184489215753),


In [117]:
sorted(list(enumerate(combined_similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(4, 0.7357640366852596),
 (10, 0.7058748402479099),
 (48, 0.6934961522946308),
 (6, 0.6555088887487255),
 (25, 0.6553300203306327)]

In [119]:
new_df[new_df['_id'] == hostels].index[19]

C:\Users\empsw\AppData\Local\Temp\ipykernel_4168\2081677972.py:1: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version. Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  new_df[new_df['_id'] == hostels].index[19]


19

In [122]:
def recommend(hostels):
    hostel_index = new_df[new_df['_id'] == hostels].index[0]
    simdistances = combined_similarity[hostel_index]
    hostel_list = sorted(list(enumerate(simdistances)), reverse=True, key=lambda x: x[1])[1:5]
    for i in hostel_list:
        print(new_df.iloc[i[0]]['_id'])

In [123]:
recommend('64c387aefc06642f2440febe')

64c38b06fc06642f2440feda
64c3916ffc06642f2440fefc
64c3b1b3cc2695cc982ef8e8
64c38c59fc06642f2440fee0


In [124]:
recommend('64c38b06fc06642f2440feda')

64c39a98fc06642f2440ff1e
64c38877fc06642f2440fec9
64c387aefc06642f2440febe
64c389d6fc06642f2440fed7


In [125]:
import pickle

In [126]:
pickle.dump(new_df,open('hostels.pkl','wb'))

In [127]:
new_df.to_dict()

{'_id': {0: '64c387aefc06642f2440febe',
  1: '64c38877fc06642f2440fec9',
  2: '64c388dbfc06642f2440fecc',
  3: '64c389d6fc06642f2440fed7',
  4: '64c38b06fc06642f2440feda',
  5: '64c38baffc06642f2440fedd',
  6: '64c38c59fc06642f2440fee0',
  7: '64c38cd4fc06642f2440fee3',
  8: '64c38d80fc06642f2440fee6',
  9: '64c38fc5fc06642f2440fef7',
  10: '64c3916ffc06642f2440fefc',
  11: '64c39289fc06642f2440feff',
  12: '64c393eefc06642f2440ff02',
  13: '64c39627fc06642f2440ff0e',
  14: '64c396dafc06642f2440ff12',
  15: '64c397b0fc06642f2440ff15',
  16: '64c3989afc06642f2440ff18',
  17: '64c399c5fc06642f2440ff1b',
  18: '64c39a98fc06642f2440ff1e',
  19: '64c39e42fc06642f2440ff2a',
  20: '64c39ebffc06642f2440ff2d',
  21: '64c39f5ffc06642f2440ff30',
  22: '64c3a1b9fc06642f2440ff36',
  23: '64c3a23bfc06642f2440ff39',
  24: '64c3a314fc06642f2440ff3e',
  25: '64c3a3aefc06642f2440ff41',
  26: '64c3a45cfc06642f2440ff44',
  27: '64c3a4eafc06642f2440ff47',
  28: '64c3a5b8fc06642f2440ff4a',
  29: '64c3a6dcfc

In [128]:
pickle.dump(new_df.to_dict(),open('hostel_dict.pkl','wb'))

In [129]:
pickle.dump(combined_similarity,open('similarity.pkl','wb'))